Feature/reservation_release merge
CFedericoDavid/g-reskilling-android-parkingApp pull request #4
Opened 2023-10-10 01:05 UTC by CFedericoDavid

This PR contains the whole structure and logic for the spot releasing screen.

- The reservations list was moved to an object in order to be shared among the different models

Release UI
<div style="inline">
<img width="163" alt="image" src="https://github.com/CFedericoDavid/g-reskilling-android-parkingApp/assets/13878290/34aa3868-25d4-4114-8903-04219e3877a5">
<img width="167" alt="image" src="https://github.com/CFedericoDavid/g-reskilling-android-parkingApp/assets/13878290/e20258ca-cc1b-4a22-b45a-a9712b436a71">
</div><br/>

Package structure
<img width="136" alt="image" src="https://github.com/CFedericoDavid/g-reskilling-android-parkingApp/assets/13878290/93a7c858-905d-4902-b4d2-cd4f66dd6e04">

Model tests
<img width="330" alt="image" src="https://github.com/CFedericoDavid/g-reskilling-android-parkingApp/assets/13878290/128a6143-5cc6-4430-8c96-025a947ba985">

Presenter tests

Screen Recordings of the app running

https://github.com/CFedericoDavid/g-reskilling-android-parkingApp/assets/13878290/2e9e16d2-588e-4d9b-8c72-7dc5d3b1647c

2023-10-10 12:27 UTC, SartiMau commented on app/src/main/java/com/fcaputo/parkingapp/mvp/model/ReleaseModel.kt
> +import com.fcaputo.parkingapp.utils.validation.ValidationErrorType.*
do not use wildcard import please

2023-10-10 12:33 UTC, SartiMau requested changes

2023-10-10 12:33 UTC, SartiMau commented on app/src/main/java/com/fcaputo/parkingapp/mvp/presenter/ReleasePresenter.kt
> +            else -> return
just in case, here you should show a general error message..

2023-10-10 12:33 UTC, SartiMau commented on app/src/main/java/com/fcaputo/parkingapp/mvp/view/ReleaseView.kt
> +        MaterialAlertDialogBuilder(activity as AppCompatActivity)
I recommend creating an AlertDialogUtils or AlertDialogFactory class, so you can abstract the creation and behavior. Doing so, from the views you will only call AlertDialogFactory.showDialog(...)

2023-10-10 13:41 UTC, matiasilveiro-gl commented on app/src/test/java/com/fcaputo/parkingapp/model/ReleaseModelTest.kt
> +        ParkingData.reservations.clear()
This `clear()` can be moved to the `setUp`

2023-10-11 11:54 UTC, FranciscoGaraventa commented on app/src/main/java/com/fcaputo/parkingapp/mvp/contract/HomeContract.kt
> +        fun onReleaseClick()
As a suggestion, the standard is to use the word `'Pressed'` instead of `'Click'`.

2023-10-11 11:55 UTC, FranciscoGaraventa commented on app/src/main/java/com/fcaputo/parkingapp/mvp/contract/HomeContract.kt
> +        fun onReleaseButton(onClick: () -> Unit)
Same as above

2023-10-11 11:55 UTC, FranciscoGaraventa commented on app/src/main/java/com/fcaputo/parkingapp/mvp/contract/ReleaseContract.kt
> +
Remove empty space

2023-10-11 12:11 UTC, FranciscoGaraventa approved these changes
Approve with minor comments

2023-10-11 13:00 UTC, matiasilveiro-gl approved these changes

2023-10-11 13:04 UTC, SartiMau approved these changes

2023-10-11 18:38 UTC, merged